### PR TITLE
Update to show new MP value on task completion

### LINKED ISSUE #421: MP value increases not shown on task completion
When I check off a task that increases my MP levels, the MP display bar continues to show the stale MP level while the HP and XP bars are updated immediately. The snackbar notifications also mention HP and XP changes but don't mention MP changes.

### PR DESCRIPTION
**Pull request by dbarnett**
Fixes #421.

### CODE REVIEW

**Comment by dbarnett** [comment]
BTW, is there a guide for creating a test user and forcing stats to different states for Android development? I created a user for testing that's apparently unrelated to my real user but has my real email associated (so I see nag emails for it sometimes), and I didn't see how to force the level above/below 11 for testing MP features.

**Comment by Alys** [comment]
@dbarnett Settings > Site > Fix Character Values (http://habitica.wikia.com/wiki/Fix_Character_Values ) lets you adjust your level. Note that adjusting level downwards doesn't reset certain flags so it doesn't always produce the same effect that you'd notice by reaching that level from going upwards.

Settings > Site also lets you delete your test account. You can then create a new one with the same login details, which can be the best way to test certain features (e.g., to test unlocking the class system for the first time).

**Comment by vIiRuS** [comment]
Thanks!

What's your habitica user ID?

**Comment by dbarnett** [comment]
User ID: 81385353-52cd-4f46-b424-007c49a00950

BTW, my last contribution in #394 also hasn't been added according to https://habitica.com/#/options/groups/hall/heroes.

**Comment by vIiRuS** [comment]
Sorry! Fixed that now.

**Pull request merged**
