### PR TITLE
Hide FloatingActionButton on scroll

### PR DESCRIPTION
**Pull request by farsidesoul**
After a certain amount of scrolling, the floating action button will hide, then a short scroll back up will bring the floating action button back into visibility.

I played with the numbers a bit, but feel the user would prefect the button to be visible for longer and hide less, so the scroll back up to bring the button back into visibility fit the best.

- kayliee

Re: https://github.com/HabitRPG/habitrpg-android/issues/234

### CODE REVIEW

**Comment by vIiRuS** [comment]
Hey,

Thanks for the PR!
One issue I found is, that the button simply disappears without animation. Maybe it could slide to the bottom when hiding and slide back up when reappearing? As to give an indication where it went and that it didn't disappear on accident.

**Comment by farsidesoul** [comment]
No worries, I'll take a look at it tonight.

**Comment by farsidesoul** [comment]
@vIiRuS I've just committed the additional changes.  The FAB now slides in and out of the bottom of the screen.  If the use hits the very bottom of the screen and continues to try and scroll, the FAB hides.  If they get to the top and keep trying to scroll, the FAB will show.  

The same logic with hiding when scrolling normally still exists.  Let me know if there are any other issues/additions you want me to make.

**Comment by vIiRuS** [comment]
Hey @farsidesoul,

Do you want to tell me your habitica user ID, so that I can count this towards your contributor tier?

**Comment by farsidesoul** [comment]
@vIiRuS Hey not sure what ID you need, social one is: ff00f8f0-e349-4b55-aeca-b74a88a5ed7d username is kayliee

**Pull request merged**
