### PR TITLE
Fixed grammar in section about release notifications.

### PR DESCRIPTION
**Pull request by eryno**
Just cleaned up the wording a bit; it was an incomplete sentence and had an errant capital before.

### CODE REVIEW

**Comment by franzejr** [comment]
@eryno, could you change that and also provide your UID, [as the others Pull Request](https://github.com/HabitRPG/habitrpg-android/pull/285) ? With this, we can merge your PR! Thanks!

**Comment by eryno** [comment]
Ahh, good point. I'm sure you're right. I'll make the change.

**Comment by eryno** [comment]
Fixed. Tried to make it a little more clear for people who aren't familiar with GitHub. Cleaned up one more sentence and a little formatting too, since I was in there anyway.

I'm assuming this comment is enough? If not, let me know and I'll submit another PR. I am not yet that familiar with GitHub myself. 

UserId: 58a2714e-7bc9-4ab3-91e5-e4572a9230e4

**Comment by vIiRuS** [comment]
Commiting to the branch of the PR is enough to update the PR, yes :)

Looks good! thanks for the fixes. I noted your contribution and you reached your first contributor tier! :tada:  Do find out more about contributor tiers, you can check here: http://habitica.wikia.com/wiki/Contributor_Rewards

**Comment by eryno** [comment]
Thank you, @vIiRuS!

**Pull request merged**
