### PR TITLE
Corrected constants w/ proper Java conventions

### PR DESCRIPTION
**Pull request by dlew**
...Mostly because they were bugging me while looking at the code.

UserId: 4334efc4-cdb2-4733-a2db-975a3d3e9824

### CODE REVIEW

**Comment by franzejr** [comment]
Thanks, @dlew. I think this is related to: https://github.com/HabitRPG/habitrpg-android/issues/75.

**Comment by franzejr** [comment]
What @negue, @vIiRuS think about this ?

**Comment by sgabler** [comment]
Not familiar with the codebase yet, but these changes make sense, in my opinion

:+1:

**Comment by vIiRuS** [comment]
Thanks for the changes! will merge this in now.

 I noted your contribution and you reached your first contributor tier! :tada: Do find out more about contributor tiers, you can check here: http://habitica.wikia.com/wiki/Contributor_Rewards

**Pull request merged**
