### PR TITLE
Guild Search Bar - Issue #513

### PR DESCRIPTION
**Pull request by jjbillings**
Added search bar to the public guilds page.
my Habitica User-ID: d5de2b4c-caa6-4927-97b2-4ad0bda7e85a (Jack Billings)

### CODE REVIEW

**Comment by jjbillings** [comment]
The search feature searches the available public guilds based on the name of the guild. We could also search with the description of the guild as well.

**Comment by vIiRuS** [comment]
Can the SearchView be moved to the actionbar? Or at least the search button. Right now it looks a bit weird having only the search icon on the left that takes up a full bar when you scroll.

**Comment by jjbillings** [comment]
I'm on it!

**Comment by jjbillings** [comment]
Should be good to go now :)

**Comment by vIiRuS** [comment]
Awesome, thanks!

I noted this as a contribution to your habitica profile

**Pull request merged**
