### PR TITLE
Updated butterknife dependency and unbinded fragment views

### PR DESCRIPTION
**Pull request by ianrumac**
I updated the butterknife dependency to 7.0.1 and the syntax changes coming with 7.0 update.
Added unbinding to fragments that used binding.

### CODE REVIEW

**Comment by negue** [comment]
Hey, 

thanks for the contribution, I also wanted to upgrade butterknife! 

And actually I didn't know I had to unbind them too .. soo :+1:

Could you maybe update to the latest develop changes?

**Comment by ianrumac** [comment]
Oh sure, no problem

On Wed, Dec 16, 2015 at 9:53 PM, negue < notifications@github.com [notifications@github.com] > wrote:
Hey,

thanks for the contribution, I also wanted to upgrade butterknife!

And actually I didn't know I had to unbind them too .. soo:+1: [https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png]

Could you maybe update to the latest develop changes?

—
Reply to this email directly or view it on GitHub
[https://github.com/HabitRPG/habitrpg-android/pull/305#issuecomment-165235890] .[https://github.com/notifications/beacon/AGWaIfVHEsu8Dis5ZpFYrS_vahRlFrLNks5pQcbDgaJpZM4G2u3f.gif]

**Comment by dlew** [comment]
You don't actually have to unbind them... I'm honestly not sure why Butterknife recommends doing it.

The only reason to unbind them would be to avoid a memory leak, but if the `Fragment` is fully removed, then there's nothing retaining the `View` anymore, either. It'd be more worrisome if you retain the `Fragment` for longer than necessary.

Maybe there's something I'm missing?

**Comment by ianrumac** [comment]
Yes, it is due to fragments leaking, mostly where strong references to fragments are kept. Not a huge concern and a must do, miniscule improvement but since I already touched on those fragments didn't see a reason not to do it.

**Comment by vIiRuS** [comment]
Awesome. Thanks!

Can you also post your Habitica user ID, so that I can note this towards your contributor tier?

**Comment by ianrumac** [comment]
@vIiRuS here it is:
f86bc361-0e17-4ff6-824c-0093f4744c86

**Comment by vIiRuS** [comment]
I noted your contribution and you reached your first contributor tier! :tada: Do find out more about contributor tiers, you can check here: http://habitica.wikia.com/wiki/Contributor_Rewards

**Pull request merged**
