### PR TITLE
feat: add GIF supported AvatarView

### PR DESCRIPTION
**Pull request by nivl4**
my Habitica User-ID: 51102111-ed4a-4f13-972b-705a3c1e5808

- change avatar image generation to custom avatar view with layers of `Drawee`
- image cache and memory management provided by default with [Fresco](http://frescolib.org/)
- add support for customizable item position eg.`weapon_special_critical`

### CODE REVIEW

**Comment by vIiRuS** [comment]
Cool!

Have you done some tests if this negatively impacts performance / memory usage?

We decided against using hungarian notation at some point and want to avoid it going forward (I still have to do a pass through the current code and fix all remaining usages). For this to get merged, could you change this? As for reasoning why, I'll refer to [Jake](http://jakewharton.com/just-say-no-to-hungarian-notation/)

Having both Picasso and Fresco feels weird. It would probably make sense to completely switch to fresco, if that provides more features while also offering everything we use from picasso.

**Comment by nivl4** [comment]
Hungarian notation removed per project coding standard.

In terms of the performance, I didn't notice any negative impacts. As image cache/memory is managed by Fresco library, if there's any performance problems it would probably be fixed in the Fresco project.
I did notice that the memory usage would increase a little bit to cache GIF frames, but would later be released/managed by Fresco. CPU usage would also increase a little bit (less than 1%) for GIF.

Before:
original

After:
new

About migrating everything to Fresco and deprecate Picasso related code, I was hoping to find time to do that in a different pull request once changes in this request has been reviewed and accepted.

**Comment by nivl4** [comment]
@vIiRuS Travis CI build failed because of the new tests added recently (Commit:
a4e7fc2682f9a2e2d2814e6d341c3a48ea0253ce), hence is outside the scope of this pull request.

**Comment by vIiRuS** [comment]
Yes, I also noticed that. I'll be traveling over the weekend, so I'll test and probably merge this in early next week.

I also agree that switching to fresco from picasso isn't necessarily in the scope of this PR. I just wanted to make sure that that was a (good) option.

**Pull request merged**
