### PR TITLE
Due dailies

### PR DESCRIPTION
**Pull request by toshevski**
I added options in settings to show only due dailies.
my Habitica User-ID: fb863d36-9101-4493-9ada-8358d781ee8a

### CODE REVIEW

**Comment by vIiRuS** [comment]
Thanks! Looking good.
Would you maybe be interested in expanding this PR, to also include the other filter options that are available on the website? That would be "Weak" and "Strong" for habits, "dated" and "done" for todos and additionally "grey" for dailies.
As for interface, the iOS app has the selection for these filters in the same view as the filter selection. And persists the selection as a preference (so similar to how you are storing it now).
img_0506

Having this also available on android would be perfect

**Comment by toshevski** [comment]
I can try to do that, but it will be same like this one with options in settings.
And I have few questions:
1. How do you classify weak and strong habits?
2. How do you classify dated and done?
3. And grey for dailies?

Do you have some functions implemented?

**Comment by vIiRuS** [comment]
Since some of these options would only be used temporarily, having them quickly accessible in the filter sidemenu would be rather important

1. weak habits are all habits with a value <= 0. Strong habits are all with a value > 0
2. dated are all todos, that are not completed and have a duedate set. Done are all completed todos
3. grey for dailies is the inverse of the due dailies

**Comment by robertpateii** [comment]
@toshevski Hi Mirche, I'm interested in helping with this feature. Have you made more progress? Waiting on the code freeze? Shall I fork your version of the repository as a starting point?

**Comment by toshevski** [comment]
@robertpateii I was busy doing some work for my faculty, also I work on one project of my own and I didn't have time for this feature. But please use my code as a starting point if it suits your needs. :)

**Comment by robertpateii** [comment]
Hi @vIiRuS, is this what you want to see for the UI?
image
(obviously "foo" should be "Done". I was just testing the click event.)

Also it seems odd to me to persist these selections as preferences. On the website these filters are stored briefly in memory and destroyed on a page reload. Also this menu is separate from the preferences menu. Can you have two preference menus? I would expect these filters would behave like the tags they're adjacent to and last as long as the app is in memory.

If the app is to behave like the website, then I would Mirche's code as is and add these filters so they behave like the tags in the app.

Does that sound right to you?

**Comment by vIiRuS** [comment]
I had unfortunately not considered that, unlike the iOS app, the filter menu is higher in the hierarchy than the individual lists and would then have to contain all three filter types. This way it looks pretty overwhelming and cramped. Ideally there would be a way to have only the matching options available in every list, so that it's simpler. But that would not fit to the drawer menu currently used for filtering.

At the time I implemented the filtering on iOS, I didn't know the website actually had a preference for settings "Due" as the default view for dailies. I made the selections persistent, because that is probably what 99% of the users would want as a behaviour for dailies. Since we haven't had any complaints about that behaviour so far, I figured we should also implement it this way on android. But if others think carrying over the behaviour from the website, I'd also be open for that.
Currently the implementation from Mirche uses a locally stored variable for the dailies filter preference. It should probably use the set from the website, to have a consistent behaviour there?

**Comment by robertpateii** [comment]
Hey Phillip,

Thanks for checking in on this issue.

I agree that *ideally* "dailies default to due" should sync with the website, but I wouldn't want to add more delay for it. Which it would since I've already resolved the merge conflict with Mirche's code. 

If you agree, here's the PR to merge: #530.

Thanks,

Robert

**Comment by robertpateii** [comment]
never mind, i killed that PR for now. Looks like the new filter actually filters out equipment rewards too. I'll poke through Mirche's code some more when I get the chance.

**Comment by vIiRuS** [comment]
@robertpateii I'm currently doing some refactoring, that will result in the equipment rewards not being affected by the filter, so you can for now assume that that is already the case.

But since the next release is a couple of days away, I would prefer to merge in a finished/complete PR instead of the current version.

Since you are taking over, I'll close this PR.

**Comment by robertpateii** [comment]
Great, thanks. In that case I re-opened the pull request with the merge conflict fixes and Mirche's code.  It should be good to go. #531

**Pull request closed without merging**
