### PR TITLE
Expanded the clickable space of the checkbox

### PR DESCRIPTION
**Pull request by farsidesoul**
Re: https://github.com/HabitRPG/habitrpg-android/issues/236

The entire left side layout that holds the checkbox can now be clicked to checkoff a daily/todo item.  

- kayliee

### CODE REVIEW

**Comment by dlew** [comment]
The canonical way of expanding a touch space is to use a [`TouchDelegate`](http://developer.android.com/reference/android/view/TouchDelegate.html) instead of just creating a larger container.

**Comment by farsidesoul** [comment]
Cheers Dan,

I've never used that before so I'll have a look into it.

**Comment by farsidesoul** [comment]
@dlew Thanks for that, I wasn't aware that was a thing.  Let me know if this isn't a correct implementation.

**Comment by vIiRuS** [comment]
Something went wrong with the manual merge, so github didn't mark this as merged. The commits are merged however.

Thanks a lot!

I noted this contribution towards your next contributor tier.

**Pull request closed without merging**
